name: dw_image_picker_android
description: Android implementation of the dw_image_picker plugin.
repository: https://github.com/DeveloperWaybee/dw_image_picker/tree/main/dw_image_picker_android
issue_tracker: https://github.com/DeveloperWaybee/dw_image_picker/issues
homepage: https://waybeetech.com/

version: 1.2.12

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dw_image_picker_platform_interface: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        package: com.waybee.dw_image_picker
        pluginClass: DWImagePickerPlugin
        dartPluginClass: DWImagePickerAndroid
